import dotenv from "dotenv";
dotenv.config();

/** @type {Array<string>} */
export const allowedOrigins = [
  "soulbp.com",
  "soulbp.com/*",
  "www.soulbp.com/*",
  "https://soulbp.com",
  "https://soulbp.com/login",
  "https://soulbp.com/",
  "http://soulbp.com/",
  "http://soulbp.com",
  "soulbp.com",
  "www.soulbp.com",
  "http://www.soulbp.com",
  "https://www.soulbp.com",
  "https://www.soulbp.com/",
  "www.soulbp.com/",
  "https://www.soulbp.com/*",
  "soulbp.com/",
  "soulbp.com/*",
  "https://soulbp.com",
  "http://localhost:3000",
  "https://localhost:3000",
  "https://craftedabcd.store/*",
  "https://craftedabcd.store",
  "craftedabcd.store",
  "http://craftedabcd.store",
  "https://craftedabcd.store/login/*",
  "craftedabcd.store/*",
  "www.craftedabcd.store",
  "https://craftedabcd.store/",
  "https://craftedabcd.store",
  "http://localhost:5173",
  "http://localhost:5173/",
  "www.localhost:5173/",
  "http://www.localhost:5173/",
];
